server:
  port: 8090
spring:
  cors:
    allowed-origins: "http://localhost:8080"
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://203.195.66.67:3306/OOAD
    username: hailong
    password: 337845818
  security:
    jwt:
      key: aukhcu
      expire: 7
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    banner: off