server:
  port: 8090
spring:
  cors:
    allowed-origins: "http://8.134.23.156:8080"
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ooad
    username: ooaduser
    password: ooadlocalhost
    hikari:
      maximum-pool-size: 1000
  security:
    jwt:
      key: aukhcu
      expire: 7
  data:
    redis:
      host: localhost
      port: 6379

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl